#!/usr/bin/env python3
"""Regenerate crates/baddel-core/src/static_layouts.rs from the real macOS layouts.

    swift scripts/dump-layouts.swift com.apple.keylayout.ABC \
        com.apple.keylayout.Arabic com.apple.keylayout.ArabicPC | python3 scripts/gen-static-layouts.py
"""
import json, sys, pathlib

NAMES = {
    "com.apple.keylayout.ABC": "ABC",
    "com.apple.keylayout.Arabic": "ARABIC_MAC",
    "com.apple.keylayout.ArabicPC": "ARABIC_PC",
}
LAYERS = ["base", "shift", "opt", "optshift"]


def lit(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 0x21 <= o <= 0x7E:
            out.append(ch)
        else:
            out.append("\\u{%x}" % o)
    return '"' + "".join(out) + '"'


data = json.load(sys.stdin)
lines = [
    "//! GENERATED by scripts/gen-static-layouts.py from the macOS keyboard layouts — do not edit.",
    "//! Index = macOS virtual keycode (0..=50). Layers: base, shift, option, option+shift.",
    "",
    "pub(crate) type Table = [[&'static str; 51]; 4];",
]
for ident, name in NAMES.items():
    layout = data[ident]
    lines += ["", f"pub(crate) static {name}: Table = ["]
    for layer in LAYERS:
        row = ", ".join(lit(s) for s in layout[layer])
        lines.append(f"    // {layer}")
        lines.append(f"    [{row}],")
    lines.append("];")
path = pathlib.Path(__file__).resolve().parent.parent / "crates/baddel-core/src/static_layouts.rs"
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {path}")
